### ISSUE TITLE
Add executables so others can try it out.

### ISSUE THREAD

**Issue by TheThirdOne** [ad510/plausible-deniability#50]
I would like to try this out but I don't really want to build it myself.

**Comment by TheThirdOne** [comment]
The unity webplayer / webgl export would probably be a really good cross platform option.

**Comment by zachlatta** [comment]
Didn't Chrome disable all plugins, killing the Unity Web Player?

On Tue, Aug 18, 2015 at 6:05 PM, Benjamin Landers <notifications@github.com>
wrote:

> The unity webplayer / webgl export would probably be a really good cross
> platform option.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ad510/plausible-deniability/issues/50#issuecomment-132407702>
> .
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by TheThirdOne** [comment]
You can enable it, but it is disabled by default.

**Comment by zachlatta** [comment]
Gotcha. Is their WebGL export good enough for most games?

On Tue, Aug 18, 2015 at 6:49 PM, Benjamin Landers <notifications@github.com>
wrote:

> You can enable it, but it is disabled by default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ad510/plausible-deniability/issues/50#issuecomment-132413995>
> .
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by TheThirdOne** [comment]
it should work, but you need Unity 5.0 to deploy it.

**Comment by ad510** [comment]
I added releases of a current version and my original game jam prototype. It took a few days because I wanted to change the license to CC0 first and I've been preoccupied with other things the last few days, so thanks for waiting.

I'd be more than happy to chat further about Plausible Deniability and other stuff if you're interested. Zach has my phone number, but text or email me before calling.

**Comment by TheThirdOne** [comment]
Thanks

**Comment by ad510** [comment]
Let me know if you have trouble figuring out the UI, since I usually explain the game in person.

You may also want to check out [Momentum Master](http://maxgames.com/play/momentum-master.html) and [Myrrored](http://kongregate.com/games/downinggames/myrrored?referrer=downinggames).
