### ISSUE TITLE
relicense as CC0 (ok, Zach?)

### ISSUE THREAD

**Issue by ad510** [ad510/plausible-deniability#51]
I want to change Plausible Deniability's license to [CC0](https://creativecommons.org/publicdomain/zero/1.0/), which is essentially worldwide public domain. This would also release [your changes](https://github.com/ad510/plausible-deniability/commits?author=zachlatta) under CC0. Are you OK with this?

**Comment by ad510** [comment]
This would also relicense [these changes](https://github.com/ad510/plausible-deniability/commits/scenario?author=zachlatta) on the scenario branch.

**Comment by zachlatta** [comment]
Yup! Please go right ahead.

On Wed, Aug 19, 2015 at 1:43 AM, Andrew Downing <notifications@github.com>
wrote:

> This would also relicense these changes
> <https://github.com/ad510/plausible-deniability/commits/scenario?author=zachlatta>
> on the scenario branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ad510/plausible-deniability/issues/51#issuecomment-132495022>
> .
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
